server:
  port: 8080
  tomcat:
        max-threads: 1000  # 最大工作线程数（根据 CPU 核心数调整，如 8 核设 800-1000）
        min-spare-threads: 200  # 最小空闲线程数
        accept-count: 2000  # 等待队列大小（超过线程数的请求放入队列，避免直接拒绝）
spring:
  application:
    name: ExamSystemApplication
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://192.168.127.128:3306/exam?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  druid:
    initial-size: 10
    min-idle: 10
    max-active: 2000
    max-wait: 6000

#    time-between-eviction-runs-millis: 60000
#    min-evictable-idle-time-millis: 300000
#    validation-query: SELECT 1
#    test-while-idle: true
#    test-on-borrow: false
#    test-on-return: false
#
#    # SQL 监控与统计
#    stat-view-servlet:
#      enabled: true
#      url-pattern: /druid/*
#      login-username: admin
#      login-password: 123456
#
#    # 防御 SQL 注入
#    wall:
#      enabled: true

  cache:
    type: redis
  data:
    redis:
      host: 192.168.127.128
      port: 6379
      database: 0
#  ai:
#    ollama:
#      base-url: http://localhost:11434
#      chat:
#        model: deepseek-r1:1.5b
mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.exam.mapper: debug
#    org.springframework.ai.chat.client.advisor: debug
#    com.clj.ai: debug


deepseek:
  api-key: sk-f7befcfc686647b795172d40d1282e1a
  base-url: https://api.deepseek.com/v1/chat/completions
